# Generated by Django 4.0.5 on 2022-07-14 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_email'),
        ('Journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Journal',
        ),
    ]
