# Generated by Django 4.0.5 on 2022-07-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Journal', '0002_rename_post_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='created_date',
            field=models.CharField(max_length=50),
        ),
    ]
